### ISSUE TITLE
Add ability to switch back in frontend

### ISSUE THREAD

**Issue by luizbills** [johnbillion/user-switching#101]
Is there currently any ability to switch back in frontend?
Why? WooCommerce blocks admin panel for customers.

**Comment by johnbillion** [comment]
Yeah there's a Switch Back link in a few places on the front end:

* In the footer of the page (CSS in your theme may mean it's not very visible)
* The Profile menu in the admin toolbar (probably not accessible to WooCommerce customers)
* The Meta sidebar widget
* The login screen at wp-login.php
* The WooCommerce login screen at `/my-account`
