### ISSUE TITLE
Does not work with RegistrationMagic

### ISSUE THREAD

**Issue by gilitos92** [johnbillion/user-switching#104]
Hi!

I can confirm that the [RegistrationMagic](https://registrationmagic.com/) plugin is not compatible with the User Switching plugin. RegistrationMagic provides multiple login and security features, which may be the reason for the incompatibility. However, the issue appears to be a general compatibility problem rather than one specific to a particular feature. When I disable RegistrationMagic, User Switching works, but even when I disable each RegistrationMagic feature individually, the issue persists, so I cannot pinpoint the issue with a specific feature.

The main problem is that users are not being switched despite the message "switch back to original user" being displayed. No error message or any other feedback is provided.

Is there anything that can be done about this?

**Comment by johnbillion** [comment]
Thanks for the report.

To be honest this is best reported to the author of Registration Magic so they can investigate. I've found in the past that when a plugin doesn't work with User Switching it's usually the case that the plugin is being overzealous with its handling of requests to wp-login.php and it prevents not only User Switching from working but also other plugins that provide features such as two factor authentication, different mechanisms for logging in, etc.

Let me know what they say.
