### ISSUE TITLE
WSAL conflict

### ISSUE THREAD

**Issue by N3rdwar3** [johnbillion/user-switching#106]
Hey I was working for a client today that was using your plug-in and when they were trying to switch users they were getting an error message. I dug into it and found that it has to do with the interaction with the WSAL plugin specifically the class-wp-log-in-out file with the user_switch_event() that gets called to the action handler. 

I saw on a forum that started last week that someone on your team was already working on this so I just thought I would add that this was fixed by changing the WSAL\...\class-wp-log-in-out\user_switch_event() function to a public static function. It looked like there was some mutual collaboration existing between those two libraries already so perhaps they wouldn't mind putting that out in a patch.

Hope this helps,
C

**Comment by N3rdwar3** [comment]
No worries,

The plugin: https://wordpress.org/plugins/wp-security-audit-log/
The forum: https://wordpress.org/support/topic/fatal-error-when-using-user-switching/

Upon rereading that link I realized that the forum is actually on the WSAL page not yours my apologies. But hopefully this can help if any of your other users are using both of these plugins.

**Comment by johnbillion** [comment]
Thanks 👍  I'll close this off then as it looks like this is an issue in WSAL and they will include a fix in their next release.
