### ISSUE TITLE
Conflict with WP Remote Users Sync Version 1.2.13 | By Alexandre Froger

### ISSUE THREAD

**Issue by L1zar** [johnbillion/user-switching#109]
Hi we are receiving a Bad Gateway error when trying to use the plugin with WP Remote User Sync
![image](https://github.com/johnbillion/user-switching/assets/68828580/3642d840-3e19-4381-9657-d861b8e8e847)

We have to have the sync plugin activated to allow us use for interoperability between sub-domains, so sadly we cannot deactivate it.

Is it possible to look into a work around for this?

**Comment by johnbillion** [comment]
Can you find out what the response is and if there's an error in your PHP or server logs?

**Comment by johnbillion** [comment]
This *may* mean that your browser has accumulated a large number of cookies for your domain and when switching to another user the extra cookies that User Switching sets pushes the header size over the limit for your server.

Can you try completely clearing the cookies in your browser for your site's domain? Then log in and try again.

**Comment by L1zar** [comment]
I cleared all cookies and cache and the problem persists.

**Comment by L1zar** [comment]
It is a conflict between the 2 plugins. If I turn one off the other works.

**Comment by johnbillion** [comment]
This is almost certainly an issue where whatever combination of plugins are in use on your site is causing the size of the HTTP response headers to exceed the limit on your server. I've seen this in the past with Nginx reverse proxies. Your best bet is to contact your web host and ask them to increase the Nginx response header size limit.

Good luck!
