### ISSUE TITLE
Logout not possible after switching & deleting users

### ISSUE THREAD

**Issue by swissspidy** [johnbillion/user-switching#11]
Just noticed this behaviour on a site running WordPress 4.3 und User Switching 1.0.7.

There were only two users registered on the site, A and B (both admins). What I did:

1. Log in as user A.
2. Switch to user B.
3. Delete user A.

**What I expected:**

Either to be logged out completely, or the switch being permanent.

**What happened:**

Immediately after deleting user A, the User Switching notice in the admin was saying _"Switched to B. Switch back to B."_ After reloading the page it now only says _"Switch back to B."_

**The problem:**

I cannot log out anymore. Everytime I try to _log out_ (not _Switch Off_!), the login form says _"You are now logged out. Switch back to B."_

Only deleting the cookies helps.

**Comment by johnbillion** [comment]
Thanks! I'll take a look soon.

**Comment by johnbillion** [comment]
Hmm, I can't reproduce this problem.

 * Are your steps to reproduce correct?
 * Does the problem persist with all your other plugins deactivated?
 * Is there anything unusual about the configuration of your install? (eg. cookies, HTTPS, multisite, etc)

**Comment by swissspidy** [comment]
The only active plugin was Akismet. Everything else is normal: no special cookie config or whatsoever, no HTTPS, no multisite. Running Twenty Eleven.

Just tried it again without Akismet and couldn't reproduce it either... Strange. The plugin must be really bug-free then! ;)

When I find time I'll test it again on a fresh install.
