### ISSUE TITLE
Request: Add notice with switch back link to Access Denied page in MultiSite

### ISSUE THREAD

**Issue by MadtownLems** [johnbillion/user-switching#116]
When a Network Administrator switches to another user and tries to visit the dashboard of a subsite they don't have access to, they get a screen that talks about how they have no privileges on the site, and a list of the sites they DO have access to. This would be a great screen to output the message about how the user is currently switched to a non-network admin, with a link to switch back.

**Comment by johnbillion** [comment]
Thanks for the suggestion. I seem to remember that there are no useful hooks on that error screen, but I will take a look.

**Comment by MadtownLems** [comment]
Perhaps admin_page_access_denied could work?
