### ISSUE TITLE
Ampersands are removed from URLs when switching to a user

### ISSUE THREAD

**Issue by IMcPwn** [johnbillion/user-switching#18]
Here is an example URL: https://www.example.com/checkout/order-pay/100/?pay_for_order=true&key=order_x82jhsx71

Then after switching the user the URL changes to: https://www.example.com/checkout/order-pay/100/?pay_for_order=true&user_switched=true

This breaks the location each time returning a 404 because the &key=order_x82jhsx71 is missing. I've looked at the code for quite some time and can't find out what is causing this.

Any help would be appreciated :)

**Comment by johnbillion** [comment]
Thanks for the report. How are you switching user from this screen?

**Comment by IMcPwn** [comment]
I am using the admin-bar-user-switching plugin (https://github.com/wpmark/admin-bar-user-switching).

**Comment by johnbillion** [comment]
Thanks, this looks like it's an issue local to the User Switching in Admin Bar plugin. /cc @wpmark

**Comment by IMcPwn** [comment]
Thanks for looking into it. I reopened the issue over there as #10. Feel free to close :)
