### ISSUE TITLE
child plugin

### ISSUE THREAD

**Issue by TweetPressFr** [johnbillion/user-switching#19]
Hi there,

Don't know if it's useful, at least it was for me https://github.com/TweetPressFr/user-switching-front maybe it could be a good sidekick for your plugin :)

Made this as child plugin. #

**Comment by garrett-eclipse** [comment]
@TweetPressFr just an FYI there's an existing plugin that works similarly;
https://wordpress.org/plugins/admin-bar-user-switching/
*Originally it just listed all users, but for massive user databases that caused issues so now it uses a search box and ajax to populate a selection list.

**Comment by TweetPressFr** [comment]
ahaha same idea pretty cool then
