### ISSUE TITLE
UI to quickly switch between users

### ISSUE THREAD

**Issue by danielbachhuber** [johnbillion/user-switching#2]
It's a bit of a pain to head to Manage Users each time. What about a UI, maybe tied to the toolbar, for quickly switching between users?

Ideally, the UI would persist when you're in a switched user, so you can quickly switch to another user without reverting to your original user.

**Comment by johnbillion** [comment]
I'm going to close this off. The [Admin Bar User Switching add-on](https://wordpress.org/plugins/admin-bar-user-switching/) now provides this functionality.
