### ISSUE TITLE
Add option to permanently switch users

### ISSUE THREAD

**Issue by swissspidy** [johnbillion/user-switching#21]
I'm not sure how many people would find this useful, but sometimes I wish there was an option to make the current switch permanent, e.g. in the notice displayed by `user_switching::action_admin_notices()`.

This could be a simple link that, when clicked, calls `user_switching_set_olduser_cookie()` to remove information about the old user.

There could also be a new `$permanent` param for `switch_to_user()`.

If such an addition doesn't sound like a good fit for the plugin, a filter inside `user_switching::action_admin_notices()` could already be useful to add such a link on my own.

**Comment by johnbillion** [comment]
Interesting point. What's the use case for this?

Happy to add a filter here if necessary.

**Comment by swissspidy** [comment]
For example, on one site we have a general network admin account and individual accounts with fewer permissions for each person.

Sometimes (let's say once a month), I need to log in with the admin account to change some stuff. Afterwards, I want to switch back to my account so I can't accidentally mess things up. This should be a permanent switch, otherwise it doesn't make much sense. Currently, I have to log out and log in as the regular user.

Or maybe you're preparing for some client training as an admin and want to switch to their user account for the actual training. The admin notice would be annoying in this case. A permanent switch would make the warning disappear.

-----

TYPO3 has had two separate buttons for this for years, but the UX wasn't great so they removed the permanent switch button [a while ago](https://forge.typo3.org/issues/62595). That's why I don't think there should be two buttons, but just a simple link in the admin notice. At least at the beginning.

**Comment by johnbillion** [comment]
I've been thinking about this and while I can see it being useful, I don't think it's a particularly common use case, and Typo3 was probably right to remove it in order to simplify the UI and UX of switching between users.

I'm going to add a couple of actions in places where they're needed to allow a plugin to add its own permanent switch link.

**Comment by johnbillion** [comment]
Version 1.1.0 introduces a `user_switching_switched_message` filter for filtering the whole message when a user has switched.
