### ISSUE TITLE
Is there a specific change from version 1.3.1 to 1.4.0? 

### ISSUE THREAD

**Issue by funnychord** [johnbillion/user-switching#28]
I use a plugin called WooCommerce Phone Orders & Manual Orders. After updating User Switching from 1.3.1 to 1.4.0, the switch user ability in this other plugin fails. However, reverting to User Switching 1.3.1 (or even deleting the plugin entirely) doesn't fix the issue. 

Is there something about the functions in User Switching that might cause it to interfere with plugins that also make use of the switch_to_user hook? Since reverting and deleting didn't correct the issue, I assume it could be a cookie or database change that isn't reverted on deletion of the User Switching plugin. 

Thank you for your help

**Comment by johnbillion** [comment]
There's nothing persistent in User Switching except for its cookies. Have you tried clearing all your cookies for the domain? 

Does "WooCommerce Phone Orders & Manual Orders" provide switching functionality or does it hook into User Switching?

**Comment by funnychord** [comment]
Thank you for the confirmation. Yes, have tried clearing cookies and figured User Switching wasn't making any database changes, but figured I would check to be sure! I appreciate your reply. 

The other plugin does not hook into User Switching to operate, but since they have a similar function (in the case of the manual orders plugin, checking out as the customer for the purpose of placing an order), I believed somehow they were conflicting. I'll continue investigating the other plugin since I don't think it's yours. : )
