### ISSUE TITLE
Conflict with Sucuri Security plugin

### ISSUE THREAD

**Issue by soderlind** [johnbillion/user-switching#29]
Multisite on Local by flywheel.
    WordPress 4.9.8
    Sucuri Security plugin (1.8.18) is network activated
    User Switching (1.4.0 ) is network activated.

When the Sucuri Security plugin is activated, I get `Sorry, you are not allowed to access this page`  when I switch to user. 

If I go back and refreshes the page, it says I'm switched to the user. So, switching works but the redirect fails(?).

Switching back to the original user works fine.

**Comment by johnbillion** [comment]
I'm not sure if User Switching can do anything about this, especially without knowing the root cause. It's probably triggered by an over-zealous rule in Sucuri.

Have you contacted Sucuri about the issue?

**Comment by soderlind** [comment]
Sorry, missed your reply. I've asked sucuri for help: https://wordpress.org/plugins/user-switching/
