### ISSUE TITLE
1.4.0: [08-Oct-2018 11:52:55 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function login_header() in /wp-content/plugins/user-switching/user-switching.php:203

### ISSUE THREAD

**Issue by lkraav** [johnbillion/user-switching#30]
Saw this crash today. First I've ever seen it. Investigating for further details later.

**Comment by johnbillion** [comment]
Gonna close this one off for now. Do let me know if you find the steps to reproduce the problem.

**Comment by lkraav** [comment]
I have Sentry installed now, will be able to provide a wicked traceback if it happens again.
