### ISSUE TITLE
Capability switch_users doesn't exist by default

### ISSUE THREAD

**Issue by naviter** [johnbillion/user-switching#31]
We have a user role "Shop Manager" for those who actually manage orders for customers. They do not have full admin privileges.

After 1.4.0 they did not see "Switch to" link anymore.

Long story short it turns out that their account needed "switch_users" capability which however did not exist. After we created that capability and enabled it for the user role Shop Manager they can now user Switch to feature again.

It was not at all obvious that a "switch_users" capability must be created manually in order for this functionality to work.

**Comment by johnbillion** [comment]
The ability to switch to a user is linked directly to the ability to edit that user. The `switch_users` capability is for fine grained control if you need it.

I believe the problem is related to a recent change in WooCommerce which means shop managers can no longer edit users.

**Comment by johnbillion** [comment]
However, the `switch_users` capability was introduced specifically for this situation, so you did the right thing.

**Comment by naviter** [comment]
Thanks. My point is that we have all the latest versions of everything and switch_users capability did not exist at all. Lukcily we use User Role Editor plugin which led us to the final solution.

Since you use this capabiltiy it would be good UX in my opinion that you would at least create it if it doesn't yet exist.

Everything works fine / as expected when it does exist.

**Comment by johnbillion** [comment]
As I mentioned, the capability doesn't need to be used by default. User Switching allows users who can edit users to switch users. It has no way of knowing that you want a shop manager to be able to switch users. The `switch_users` capability is explicitly for this situation.
