### ISSUE TITLE
Could not switch users

### ISSUE THREAD

**Issue by crstauf** [johnbillion/user-switching#34]
*** on `develop` branch ***

<img width="828" alt="screen shot 2019-02-15 at 9 33 26 pm" src="https://user-images.githubusercontent.com/4573033/52893358-63f77680-3169-11e9-8ace-d0a536dda6d5.png">

I switched off my user, but still have access to the admin...? Clicking "Switch back" throws the above error.

Maybe QM and User Switching are having a sibling feud? ;)

**Comment by johnbillion** [comment]
Can you try deactivating all your other plugins to see if the problem persists? If you've got an object caching plugin in place, try that first.
