### ISSUE TITLE
Use of undefined constant when clearing old user cookies

### ISSUE THREAD

**Issue by ThomasGRIM** [johnbillion/user-switching#40]
Hi,

I'm hitting the following error message on PHP 7.3.5:
`Use of undefined constant USER_SWITCHING_OLDUSER_COOKIE - assumed 'USER_SWITCHING_OLDUSER_COOKIE' (this will throw an Error in a future version of PHP)
`

That constant is defined in the plugins_loaded action, so it should be defined just fine ahead of time. Here is the relevant part of the stack, with the plugins_loaded call being run way back:
```
stack: Array(11)
0: "user_switching_clear_olduser_cookie()"
1: "do_action('wp_login')"
2: "xxxxxxxxxxxxxxxxxxxxxxx"
3: "apply_filters('determine_current_user')"
4: "_wp_get_current_user()"
5: "wp_get_current_user()"
6: "get_user_locale()"
7: "determine_locale()"
8: "load_plugin_textdomain()"
9: "Freemius::_load_textdomain()"
10: "do_action('plugins_loaded')"
```

The blanked out part above is a custom function of mine that checks for an SSO cookie and autologins the user if the cookie is valid. Here it is, simplified:
```
add_action('determine_current_user', function ( $user_id ) {
	$found_user = get_user_from_sso_cookie();
	if ( !empty( $found_user->ID ) ) {
		error_log( '<sso> LoggedIn: '.esc_attr( $found_user->user_email ) );
		wp_set_current_user( $found_user->ID );
		wp_set_auth_cookie( $found_user->ID );
		do_action( 'wp_login', $found_user->user_login, $found_user );
		return $found_user->ID;
	}
});
```

Note that the plugins works correctly apart from this error, I can still switch between users just fine, I just get this error in my logs from time to time. Ping me if you need more information, and thanks for your work on this plugin.

Cheers,
Thomas

**Comment by johnbillion** [comment]
Thanks for the report. Can you check the priority of the Freemius action? It might be firing with a priority lower than 10, which means it fires before the `action_plugins_loaded()` method in User Switching.

**Comment by ThomasGRIM** [comment]
Hmm the Freemius step comes from the Error Log Monitor plugin (https://fr.wordpress.org/plugins/error-log-monitor/).

Tracking down how it runs is a bit painful because there's a custom subframework involved, but here is the gist of it:

In the plugin's main file:
`new Elm_Plugin(__FILE__);`

In that class's constructor:
```
if ( did_action('plugins_loaded') > 0 ) {
	$this->loadTextDomain();
} else {
	add_action('plugins_loaded', array($this, 'loadTextDomain'));
}
```

Then the actual textdomain call:
```
public function loadTextDomain() {
	load_plugin_textdomain('error-log-monitor', false, basename(dirname($this->pluginFile)));
}
```

The plugin's add_action fires either fully after plugins_loaded or during plugins_loaded with WP's default priority of exactly 10

**Comment by johnbillion** [comment]
Thanks.

I'm not sure if this is a problem with the code in Freemius or not, it's a bit hard to tell and I don't want to spend too much time on it, but I'll see whether it's possible to change the priority that User Switching uses to `1` so it fires first.

I'll need to do some testing to make sure it doesn't break anything else.

**Comment by johnbillion** [comment]
@ThomasGRIM In the `develop` branch I've changed the priority of User Switching's action to `1`. See: https://github.com/johnbillion/user-switching/commit/7405afa66fe41285d0631f4888b7b7c87c3a5c50 .

Can you give this a try on your site and see if it resolves your particular problem?

**Comment by ThomasGRIM** [comment]
Thanks a lot John and sorry for the delay.
I'll try within days and report back to you.

**Comment by ThomasGRIM** [comment]
Hi, everything seems alright now: the plugin still works and I haven't had any new notices since I changed the filter's priority.
Thanks a lot! - Thomas
