### ISSUE TITLE
Sorry to open another ticket - this is not server config related

### ISSUE THREAD

**Issue by billium99** [johnbillion/user-switching#46]
Hello - I'm sorry to say, I don't know what was updated recently, but the site is currently operating with all up-to-date plugins, and Woo Commerce Shop Managers trying to use User Switching is now failing with 502 Bad Gateway error. Server logs aren't showing anything obvious that I can say relates to these events.

Crucially, we have users like me, who can login as admin, switch users perfectly, and it works, but if I switch to Shop Manager and try to use Switch To, I'll get the exact same error. 

If it's server config, why would it only affect Shop Manager roles?

Thanks

**Comment by johnbillion** [comment]
Please don't open multiple tickets.
