### ISSUE TITLE
Even if I switched the user, I remain the origin user

### ISSUE THREAD

**Issue by ocager** [johnbillion/user-switching#50]
Hi John,

using your plugin User Switching for years on our internal corporate page (Intranet) with pleasure as it made my work supporting the users easier. Unfortunately, the plugin is not working on our page since some months and I do not exactly why.

Description:
- Going to the user section and click for another user on "Switch to" (Screenshot 1)
- The page reloads, no error message and in WP Admin on the top of the page, there appears the message "Switch back to my user", so it seems that it worked, but, looking on the wpadminbar and also the current user infos, it's my origin user shown and not the user I switched to (Screenshot 2)

![001](https://user-images.githubusercontent.com/30630832/74008771-fc41c900-4981-11ea-81cb-ed4741492d75.jpg)

![002](https://user-images.githubusercontent.com/30630832/74008784-06fc5e00-4982-11ea-9f0b-36f458d24c1d.jpg)

As I've tested your plugin in a clean wordpress installation, it worked well there and I assume that the reason is linked to my page. So I switched to a WP Origin Theme, disabled all plugins (with exception of ACF Pro and your up-to-date User Switching), removed all users with exception of mine and another for testing purposes. But it's still the same situation.

Don't know how to proceed. Do you have any ideas what might be the reason?

Best
Oli

**Comment by johnbillion** [comment]
* Does the problem persist if you switch to one of the default themes such as TwentyTwenty? If so, it could be a problem with your theme.
* Do you have a custom login URL?
* Do you have object caching in place?
* Do you have any security plugins active?
* Do you have any mu-plugins which might be interfering?

They're the things I would take a look at.

**Comment by ocager** [comment]
Okay, did some more tests in the local environment and it seems to be linked to the used plugin "[Authorizer](https://wordpress.org/plugins/authorizer/)". We are using it for SSO and it worked together with User Switching very well for years, but since some months no more. But this is not an issue of your plugin. So I would say let's close that.

Thanks for your quick reply!
