### ISSUE TITLE
Switching back fails when using BackupBuddy from iThemes

### ISSUE THREAD

**Issue by Netzie** [johnbillion/user-switching#51]
Hi
Thanks for a great plugin that I enjoy using. 
But I noticed that iThemes BackupBuddy (or iThemes Security PRO) is preventing me from returning back to my admin account.
The combination with Yoast SEO Pro could also be an issue - due to the roles mix match! (Yoast creates some new roles "SEO Admin" etc. and mixed with Danish and some other language - iThemes interpret them different? So normal access "No Role on this Board" or subscriber becomes "SEO Admin" !!!

Have a good one

Netz

**Comment by johnbillion** [comment]
Sorry to hear that.

It's most likely iThemes Security blocking cookies. You should get in touch with the iThemes team and see if they can look into the issue.

Unfortunately I can't add support to User Switching for every security, performance, and login customisation plugin out there that modifies the login functionality.
