### ISSUE TITLE
Hook to filter the switch to user link

### ISSUE THREAD

**Issue by raftaar1191** [johnbillion/user-switching#53]
Need a filter to sort the switch to URL link, So if we custom admin do not want to allow the switch to this user role or user then they can use this filter

**Comment by johnbillion** [comment]
Thanks for the issue @raftaar1191, I've commented on your PR. Cheers!

**Comment by raftaar1191** [comment]
Hey, @johnbillion I created this filter so that admin can sort the switch user button option on user role.

Example: If there are three role Admin, Editor, and Author. By default we allow all the user to switch to diff account 


But I do not want the author user to switch to editor user role but editor user role can switch to author role
