### ISSUE TITLE
COOKIE_DOMAIN causing 404

### ISSUE THREAD

**Issue by neillaferty** [johnbillion/user-switching#58]
Hello,

We are setting the COOKIE_DOMAIN in wp-config.php to allow support for subdomains. For example:

define( 'COOKIE_DOMAIN', '.mysite.com' );

This appears to break the user switching plugin. Specifically, we receive a 404 or "could not switch users" error when trying to switch.

Do you know of any workaround for this?

Thanks!
Neil

**Comment by johnbillion** [comment]
Can you provide some more info about what your intention is for supporting subdomains? What's your setup look like?

**Comment by neillaferty** [comment]
Hi John,

Thanks for the reply.

We need to access WordPress cookies such as wp_login*** in our sub-domain in order to validate and fetch User Info through WordPress rest api. In order to the browser pass these cookies to our sub-domain, we need to set the cookie's domain to allow sub-domains like ".my-site.com"

We have an app on a subdomain that needs to scrape this information.

I tried clearing all browsing data, starting from a private tab, etc., all with the same result.

Thanks!
Neil

**Comment by johnbillion** [comment]
My understanding of the behaviour of cookies on subdomains is that the leading period on the domain is not needed in order to allow a subdomain to access a cookie, as long as the cookie domain is set, which it is.

By that I mean `define( 'COOKIE_DOMAIN', 'mysite.com' )` without the period prefix should work and allow your subdomain access to the cookies.

Aside from that, I don't know why this configuration doesn't work and it's not something that I can spend time looking into, sorry!

**Comment by neillaferty** [comment]
Hi John,

I see you closed the issue which is fine. Thought you might like to know, it turns out the error was *really* a 502 so we used your replies on other issues involving 502s to resolve the problem. Working fine now.

Thank you, be well!

Neil

**Comment by johnbillion** [comment]
Thanks for the update, that problem does pop up from time to time.

**Comment by micahnz** [comment]
Noting this is still an issue and causes 502, 

> My understanding of the behaviour of cookies on subdomains is that the leading period on the domain is not needed in order to allow a subdomain to access a cookie, as long as the cookie domain is set, which it is.
> 
> By that I mean `define( 'COOKIE_DOMAIN', 'mysite.com' )` without the period prefix should work and allow your subdomain access to the cookies.

This is not the case, the period prefix is required to access on a subdomain, we use this where we need to share WP auth with non WP back-ends and COOKIE_DOMAIN must be set with the prefixed period but leads to the 502 as mentioned in the browser, if I do the request from curl I get this back as 403

```
<body id="error-page">
        <div class="wp-die-message">Could not switch users.</div></body>
</html>
```
