### ISSUE TITLE
Feature request: Add user switching to Stream

### ISSUE THREAD

**Issue by soderlind** [johnbillion/user-switching#61]
User story: As a (super) admin, when I view my [stream](https://wordpress.org/plugins/stream/), I can switch to the user listed.

I guess it should/could be solved in a separate plugin, e.g. user-switching-stream :)

**Comment by lkraav** [comment]
You mean an integration with https://github.com/johnbillion/user-switching/ or?

**Comment by johnbillion** [comment]
Good idea and thanks for the suggestion, but this isn't something I'm too interested in supporting directly in the User Switching plugin. It doesn't sound like much but it increases the support and maintenance burden somewhat. I regret adding the integrations for BuddyPress, bbPress, and WooCommerce for this reason, although the latter is sufficiently popular to make it worthwhile.

Can you click through to the user from the Stream event and then click `Switch to` from there?

**Comment by soderlind** [comment]
Yes, I can click on "edit user", which brings me to the user edit profile page and there select "switch to".

**Comment by johnbillion** [comment]
Cool, in that case I'll close this off. Thanks for the suggestion!
