### ISSUE TITLE
Switch back function not working.

### ISSUE THREAD

**Issue by kaliey06** [johnbillion/user-switching#65]
Hi, 

I am having a problem with switching back from the customer account to the admin dashboard.  When I click the switch back at the bottom of the web page, the page flashes briefly and the switch back link is gone but I am still on the customer's profile. I have tried disabling all plugins and turned off cloudflare but the plugin is still not working. Sometimes, the "The link you followed has expired." error has also popped up after trying to switch back or we end up in a loop where we keep getting redirected back to the wordpress my-account page,  Currently we are using a run-around solution where we use the toolbar at the top to return to the dashboard, but this is only a temporary solution. We do not want to enable the toolbar for everyone, only the admins. Could it be a cookies or a caching problem?  Please help.

**Comment by johnbillion** [comment]
This sounds like a caching problem on your site. The link the in admin toolbar is identical to the link in the footer.

* Do you cache front end pages for logged in customers?
* Did you remove mu-plugins too?
* Is there an advanced-cache.php file in your wp-content directory?
* Does the problem remain if you switch to one of the default themes such as Twenty Twenty?
