### ISSUE TITLE
permanent error by returning from switched user

### ISSUE THREAD

**Issue by KaTho-4056** [johnbillion/user-switching#66]
Bug details:
==========
An error of type E_ERROR was caused in line 721 of the file /usr/www/users/buchbim/neu/wp-content/plugins/user-switching/user-switching.php. 

Error message: Uncaught TypeError: Argument 1 passed to user_switching :: filter_removable_query_args () must be of the type array, null given, 
called in /usr/www/users/buchbim/neu/wp-includes/class-wp-hook.php on line 287 
and defined in /usr/www/users/buchbim/neu/wp-content/plugins/user-switching/user-switching.php:721

Stack trace:
#0 /usr/www/users/buchbim/neu/wp-includes/class-wp-hook.php(287): user_switching->filter_removable_query_args(NULL)
#1 /usr/www/users/buchbim/neu/wp-includes/plugin.php(206): WP_Hook->apply_filters(NULL, Array)
#2 /usr/www/users/buchbim/neu/wp-includes/functions.php(1216): apply_filters('removable_query...', Array)
#3 /usr/www/users/buchbim/neu/wp-content/plugins/user-switching/user-switching.php(804): wp_removable_query_args()
#4 /usr/www/users/buchbim/neu/wp-content/plugins/user-switching/user-switching.php(268): user_switching::remove_query_args('https://neu.buc...')
#5 /usr/www/users/buchbim/neu/wp-content/plugins/user-switching/user-switching.php(209): user_switching::get_redirect(Object(WP_Us ....

My software is:
WordPress version 5.5.3
Current theme: GeneratePressChild (Version 1.0)
Current plugin: User Switching (Version 1.5.6)
PHP version 7.4.13

Else I like your plugin very handy. Thanks for it. Cheers KaTho

**Comment by johnbillion** [comment]
This means another plugin on your site is adding a filter to `removable_query_args` and returning `null`, which is not an allowed value for this filter. This is a developer error.

Unfortunately the only way to find out which plugin is causing the problem is to deactivate all your other plugins one by one until the error no longer appears.
