### ISSUE TITLE
Can I disable this for Admins and Leave open for WOO Accounts?

### ISSUE THREAD

**Issue by feedingstitches** [johnbillion/user-switching#74]
Plugin Works Flawlessly - however, just a quick question about - limits - disabling it from admins that might be working on something sensitive - like inventory.

example -  I have 2FA installed for my peace of mind.

again for the woo store  - 5.7.2. WP it works like a beast - great plugin high 5!
any feedback would be appreciated.

**Comment by johnbillion** [comment]
Yes you can do this but you'll need to write some code for it. I've provided a few FAQs related to customising access to User Switching, take a look here: https://wordpress.org/plugins/user-switching/faq and in particular this FA about removing access: https://wordpress.org/plugins/user-switching/#can%20the%20ability%20to%20switch%20accounts%20be%20denied%20from%20users%3F
