### ISSUE TITLE
Consider using $_GET instead of $_REQUEST

### ISSUE THREAD

**Issue by maximejobin** [johnbillion/user-switching#75]
First, thank you for this great plugin.

I opened a [support ticket](https://wordpress.org/support/topic/getting-404-when-clicking-on-switch-to/) on WordPress that I will put here:

> We’ve used the plugin on our website for 2 year… never had an issue.
> 
> A couple of days ago, we updated the following plugins:
> WooCommerce => 5.3 to 5.4.1
> Admin Columns Pro => 5.5.2
> Storefront => 3.7.0
> 
> Since then, clicking on “Switch to” produces 404 not every time… but really often.
> 
> I’ve noticed that when the 404s happen, the plugin did not create the cookies (wordpress_user_sw_*).
> 
> There are absolutely no errors in debug.log.
> 
> I’ve created a dev website but cannot reproduce, at this point, the error.
> 
> Any tips or suggestions about that problem? Are we the only ones?

Your answer:

> Is the 404 shown for the wp-login.php page or for the page you get redirected to afterwards?
> 
> Not sure what the problem could be but the best advise is to try deactivating your other plugins one by one to see if you can identify the culprit.

My answer:

> I see this link in the address bar:
> https://xxxxxx/wp-login.php?action=switch_to_user&user_id=1145&nr=1&_wpnonce=d6b4fb8b2
> 
> … and the 404 page is displayed.
> 
> When it works, we are redirected to WooCommerce account page.

I thought updating a plugin had fixed the issue. It did not.

I did more digging and edited your code to trace it as this happens only on a production server I do not control. In dev, I wasn't able to reproduce the problem:

![image](https://user-images.githubusercontent.com/1080760/123280440-c483e480-d4d6-11eb-9d8b-4dfbb81476b8.png)

Then, I tried a "Switch to" and logs showed this:

![image](https://user-images.githubusercontent.com/1080760/123280731-06148f80-d4d7-11eb-8e4b-9162683e7f75.png)

The line in red should have triggered step 2 and step 3 in the logs. It did not.

I replaced all `$_REQUEST` by `$_GET` in the code. So far, the problem is gone... but I will try it for multiple days before claiming it really solved it.

Any reason why you are using `$_REQUEST` instead of `$_GET`?

**Comment by johnbillion** [comment]
If `$_GET['action']` is present but `$_REQUEST['action']` is not then something on your site is breaking the `$_REQUEST` superglobal in a bad way. It might be a red herring though, to be honest. If the `action` parameter contains a value that isn't handled by either User Switching or WordPress core then you should see the default login screen, not get a 404.

Did you try deactivating your other plugins? I know it's not fun if you are only seeing the problem on a production site, but that's about your only option. Start with plugins that affect the login system, security, that sort of thing.

You could also look at hooking some debugging information into the `set_404` action and try to log the stack trace to see what triggers it.
