### ISSUE TITLE
Allow switching between some accounts?

### ISSUE THREAD

**Issue by estudioalfa** [johnbillion/user-switching#76]
Hello!

First of all, thank you very much for your time! This plugin is great!

I am working on a project and I need to allow managers to switch only to the accounts associated with each of them.

Is there any way to achieve it? Any clue with a custom development?

Thanks so much in advance!

Best Regards!

**Comment by johnbillion** [comment]
Yes this is possible via the capability filters, although you do need to be comfortable using the roles and capabilities API in WordPress to make changes there.

Take a look at the plugin FAQ and also here for an example of conditionally allowing users to switch based on the target user: https://github.com/johnbillion/user-switching-for-regular-admins/blob/master/usfra.php
