### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by Daronspence** [johnbillion/user-switching#8]
`WP_Admin_Bar::add_node was called with an argument that is deprecated since version 3.3! Use my-account as the parent for the switch-off admin bar node instead of my-account-with-avatar.`

I saw there was a `wordpress.org` forum post about this a few years ago and it looked to be resolved but I ran into it today. I'm using the [TGM Plugin Activation Class](https://github.com/thomasgriffin/TGM-Plugin-Activation) to install some plugins and I noticed this error was being thrown on the pages that TGM generates. I've gone into TGM to try and figure this out, but it seems that TGM is only calling `WP_List_Table`. 

Thanks to your other handy plugin, Query Monitor, I can see the stack trace is going back to `user_switching->action_admin_bar_menu()` which doesn't make a lot of sense since the admin bar is supposed to be decoupled from the admin page's content (right?). Calling `remove_action` on that function gets rid of the error. I can add it to the plugin I'm working on but it seems like a better approach to find the root cause whatever it is. :)

Do you know what causes that error to be thrown? I tried to make sense of the logic but I'm afraid I don't know enough about WP's past to make sense of what's happening. 

Great plugin btw :) not a super huge issue, just curious is all!

**Comment by Daronspence** [comment]
oh! Good news! I just tested this again, and the error is not present in a non-multisite install. Maybe that has something to do with it?

**Comment by johnbillion** [comment]
Are you running some code which hides the user profile menu in the admin bar? This is the only situation I can think of that would cause [this logic](https://github.com/johnbillion/user-switching/blob/1.0.5/user-switching.php#L355-L361) to use `my-account-with-avatar` as the menu parent. If that's the case then I can tweak that logic a bit.

Somehow I missed the notification for this issue Daron. Sorry about that.
