### ISSUE TITLE
How to create custom link in plugin

### ISSUE THREAD

**Issue by twixi** [johnbillion/user-switching#82]
I want to create 2 custom buttons im wp custom profiles plugin:

`
/profile/login/?action=switch_to_user&user_id=17&nr=1&_wpnonce=215bbb149b
to:
< a href="/profile/< ? php switch_to_user code ? >">Swith to user<   /a>

/profile/login/?action=switch_to_olduser&nr=1&_wpnonce=a7c824e394
to:
< a href="/profile/< ? php switch_to_olduser code ? >">Swith to back<  /a>
`

**Comment by johnbillion** [comment]
Yep you can do this, details here: https://wordpress.org/plugins/user-switching/#can%20i%20add%20a%20custom%20%22switch%20to%22%20link%20to%20my%20own%20plugin%20or%20theme%3F
