### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by Jixart** [johnbillion/user-switching#92]
I am using cloudflare on my Dokan marketplace and when trying to switch to a vendor i have a 502 gateway error. Any specific parameters to add on cloudflare or have you ever experienced such issue ?

**Comment by johnbillion** [comment]
This is usually a side effect of the extra cookies that User Switching sets in your browser, but it's not specific to user switching as any plugin that adds cookies can trigger this problem. Take a look through these threads for more info: https://wordpress.org/search/502+intext%3A%22Plugin%3A+User+Switching%22/
