### ISSUE TITLE
Error filter_woocommerce_account_menu_items expect array

### ISSUE THREAD

**Issue by hrangel1126** [johnbillion/user-switching#98]
Error found in Wordpress 6.1.1 and woocomerce 7.0 Error **filter_woocommerce_account_menu_items** expect array

fixed in user-switching.php line 1058 add to functio to accept NULL by chaign the fcuntion as below

**From**
public function filter_woocommerce_account_menu_items( array $items ) 
**To**
	public function filter_woocommerce_account_menu_items( array $items = NULL )

**Comment by johnbillion** [comment]
Thanks for the report. WooCommerce passes an array to the `woocommerce_account_menu_items` filter so there must be a plugin on your site that is incorrectly returning `null` from this filter. Try deactivating your other plugins one by one to see if you can find the culprit.
